name: Smith Chemical and Wax
favicon: null
layout_spectrum: 0.650103164371103
typography_spectrum: 0.33755051740445197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0437054093927145
  lightness: 0.6456308052875102
  saturation: 0.6070271220523864
  rhythmicContrast: 0.35051637329161167
purpose: []
