name: Smith Chemical and Wax
favicon: null
layout_spectrum: 0.22819
typography_spectrum: 0.33755051740445197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b5399'
    - '#72b549'
    - '#bbdba7'
    - '#6783b6'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.6070271220523864
  rhythmicContrast: 0.35051637329161167
purpose: []
